// web/src/pages/Email/Email.tsx
import React from "react";
import "./Email.css";
import { Footer, Header } from "../../components";
import { baseUrl } from "../../constants";
import { useParams } from "react-router-dom";
interface Props {}
const Email: React.FC<Props> = () => {
  const params = useParams<{ subject: string }>();

  const [state, setState] = React.useState({
    firstName: "",
    lastName: "",
    body: "",
    sender: "",
    phoneNumber: "",
    loading: false,
    message: "",
    error: "",
    subject: "",
  });
  const sendEmail = async (e: React.FormEvent) => {
    e.preventDefault();
    setState((s) => ({ ...s, loading: true }));
    try {
      if (state.subject === "") {
        setState((s) => ({
          ...s,
          error: "Email subject is required.",
          message: "",
          loading: false,
        }));
        return;
      }
      if (state.firstName === "") {
        setState((s) => ({
          ...s,
          error: "First Name(s) is required.",
          message: "",
          loading: false,
        }));
        return;
      }
      if (state.lastName === "") {
        setState((s) => ({
          ...s,
          error: "Last Name is required.",
          message: "",
          loading: false,
        }));
        return;
      }
      if (state.body.length < 10) {
        setState((s) => ({
          ...s,
          error: "The email body must have at least 10 characters.",
          message: "",
          loading: false,
        }));
        return;
      }
      if (state.sender === "") {
        setState((s) => ({
          ...s,
          error: "Please enter your email address.",
          message: "",
          loading: false,
        }));
        return;
      }

      if (state.phoneNumber === "") {
        setState((s) => ({
          ...s,
          error: "Your Phone Number is required.",
          message: "",
          loading: false,
        }));
        return;
      }
      setState((s) => ({ ...s, message: "", error: "", loading: false }));
      const res = await fetch(`${baseUrl}/api/v1/send-email`, {
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          subject: state.subject,
          body: state.body,
          from: state.sender,
          firstName: state.firstName,
          lastName: state.lastName,
          phoneNumber: state.phoneNumber,
        }),
        method: "POST",
      });
      const data = await res.json();
      if (data.code === 500) {
        setState({ ...state, message: "", error: data.message });
        return;
      }
      setState((s) => ({ ...s, message: "The email was sent successfully." }));
    } catch (err) {
      setState((s) => ({ ...s, error: "Couldn't send the email try again." }));
    } finally {
      setState((s) => ({ ...s, loading: false }));
    }
  };

  React.useEffect(() => {
    setState((s) => ({ ...s, subject: params.subject || "" }));
  }, [params]);

  return (
    <div className="email">
      <Header />
      <div className="email__main">
        <form onSubmit={sendEmail}>
          <h1>Send us an Email.</h1>

          {state.loading && (
            <div className="email__loader">
              <div />
            </div>
          )}

          <input
            type="text"
            placeholder="subject"
            value={state.subject}
            onChange={(e) =>
              setState((s) => ({ ...s, subject: e.target.value }))
            }
          />

          <div>
            <input
              type="text"
              placeholder="your first name(s)"
              value={state.firstName}
              onChange={(e) =>
                setState((s) => ({ ...s, firstName: e.target.value }))
              }
            />
            <input
              type="text"
              placeholder="your last name"
              value={state.lastName}
              onChange={(e) =>
                setState((s) => ({ ...s, lastName: e.target.value }))
              }
            />
          </div>

          <textarea
            placeholder="type your message"
            value={state.body}
            onChange={(e) => setState((s) => ({ ...s, body: e.target.value }))}
          />

          <input
            type="email"
            placeholder="your email address"
            value={state.sender}
            onChange={(e) =>
              setState((s) => ({ ...s, sender: e.target.value }))
            }
          />

          <input
            type="tel"
            placeholder="your phone number"
            value={state.phoneNumber}
            onChange={(e) =>
              setState((s) => ({ ...s, phoneNumber: e.target.value }))
            }
          />
          {state.error && (
            <p className="email__message--error">{state.error}</p>
          )}
          {state.message && <p className="email__message">{state.message}</p>}
          <button type="submit">SEND</button>
        </form>
      </div>

      <Footer />
    </div>
  );
};

export default Email;

// frontend/src/views/Email/Email.vue
<template>
  <div class="email">
    <Header />
    <div class="email__main">
      <form @submit.prevent="sendEmail">
        <h1>Send us an Email.</h1>
        <div class="email__loader" v-if="loading">
          <div />
        </div>
        <input type="text" v-model="title" placeholder="subject" />
        <div>
          <input
            type="text"
            placeholder="your first name(s)"
            v-model="firstName"
          />
          <input type="text" placeholder="your last name" v-model="lastName" />
        </div>
        <textarea v-model="body" placeholder="type your message"></textarea>
        <input type="email" v-model="sender" placeholder="your email address" />
        <input
          type="tel"
          v-model="phoneNumber"
          placeholder="your phone number"
        />
        <p v-if="error" :class="error ? 'email__message--error' : ''">
          {{ error }}
        </p>
        <p v-if="message" :class="message ? 'email__message' : ''">
          {{ message }}
        </p>
        <button type="submit">SEND</button>
      </form>
    </div>
    <Footer />
    <CookiePolicy v-if="cookiesAccepted === false" />
  </div>
</template>

<script>
import { CookiePolicy, Header, Footer } from "../../components";
import { baseUrl } from "../../constants";
export default {
  props: {},
  components: {
    CookiePolicy,
    Header,
    Footer,
  },
  computed: {
    cookiesAccepted() {
      return this.$store?.state?.cookies;
    },
  },

  data() {
    return {
      title: this.$router.history.current.params?.category,
      body: "",
      sender: "",
      error: "",
      firstName: "",
      lastName: "",
      phoneNumber: "",
      message: "",
      loading: false,
    };
  },
  methods: {
    sendEmail() {
      this.loading = true;
      if (this.title == "") {
        this.message = "";
        this.error = "Email subject is required.";
        this.loading = false;
        return;
      }
      if (this.firstName == "") {
        this.loading = false;
        this.message = "";
        this.error = "First Name(s) is required.";
        return;
      }
      if (this.lastName == "") {
        this.message = "";
        this.error = "Last Name is required.";
        this.loading = false;
        return;
      }
      if (this.body.length < 10) {
        this.message = "";
        this.loading = false;
        this.error = "The email body must have at least 10 characters.";
        return;
      }
      if (this.sender == "") {
        this.loading = false;
        this.message = "";
        this.error = "Please enter your email address.";
        return;
      }

      if (this.phoneNumber == "") {
        this.message = "";
        this.loading = false;
        this.error = "Your Phone Number is required.";
        return;
      }
      this.message = "";
      this.error = "";

      (async () => {
        this.loading = true;
        await fetch(`${baseUrl}/api/v1/send-email`, {
          headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            subject: this.title,
            body: this.body,
            from: this.sender,
            firstName: this.firstName,
            lastName: this.lastName,
            phoneNumber: this.phoneNumber,
          }),

          method: "POST",
        })
          .then((res) => res.json())
          .then((d) => {
            this.loading = false;
            if (d.code == 500) {
              this.message = "";
              this.error = d.message;
            } else {
              this.error = "";
              this.message = d.message;
            }
          })
          .catch((error) => {
            this.loading = false;
            this.error = error.message;
          });
      })();
    },
  },
};
</script>

<style scoped lang="scss">
.email {
  .email__main {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    min-height: 60vh;
    form {
      padding: 10px;
      display: flex;
      flex-direction: column;
      width: 100%;
      max-width: 400px;
      margin: auto;
      position: relative;
      .email__loader {
        position: absolute;
        top: 0;
        height: 100%;
        right: 0;
        left: 0;
        right: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        z-index: 100;
        div {
          width: 30px;
          height: 30px;
          border-radius: 50%;
          border: 3px solid lightgray;
          border-top: 3px solid #42b983;
          border-right: 3px solid cornflowerblue;
          animation: loading 1s ease 0s infinite;
        }
      }
      h1 {
        width: 100%;
        padding: 10px;
        text-align: center;
        letter-spacing: 2px;
        font-size: 0.9rem;
        text-transform: uppercase;
        user-select: none;
        position: sticky;
        top: 0;
        z-index: 10;
        background: white;
      }
      div {
        width: 100%;
        display: flex;
        margin: 5px auto;
      }
      input,
      textarea,
      div > input {
        border: 1px solid cornflowerblue;
        outline: none;
        padding: 5px;
        resize: none;
        border-radius: 5px;
      }
      div > input {
        flex: 1;
      }
      div > input:first-of-type {
        margin-right: 5px;
      }
      input:last-of-type {
        margin-top: 5px;
      }
      textarea {
        margin: 10px 0;
        height: 200px;
      }
      button {
        margin: 10px auto;
        padding: 5px;
        background: cornflowerblue;
        cursor: pointer;
        color: white;
        border-radius: 5px;
        width: 100%;
        &:hover {
          background: #42b983;
        }
      }
      .email__message,
      .email__message--error {
        margin: 10px auto;
        user-select: none;
        background-color: #42b983;
        width: 100%;
        color: white;
        padding: 5px;
        border-radius: 5px;
        text-align: center;
      }
      .email__message--error {
        background-color: red;
      }
      .email__message {
      }
    }
  }
}

@keyframes loading {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
</style>
